config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    unlocks: "users/unlocks"
  }

  devise_scope :user do
    get '/users/add_coach' => 'users/registrations#add_coach'
    post '/users/add_coach' => 'users/registrations#create_coach'
    get '/users/add_player' => 'users/registrations#add_player'
    post '/users/add_player' => 'users/registrations#create_player'
  end

  get '/pages/:id' => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'

  get '/dashboard' => 'dashboard#index_for_coach', constraints: lambda { |request| request.env['warden'].user.is? :coach  }
  get '/dashboard' => 'dashboard#index_for_player', constraints: lambda { |request| request.env['warden'].user.is? :player }
  get '/dashboard' => 'dashboard#index', as: :user_root

  resources :dashboard, only: [:index] do
    put :update_yaybar_hidden_state, on: :collection
  end

  resources :clubs, only: [] do
    collection do
      get :choose_subscription_plan
      post :activate_subscription_plan
      get :players
    end
  end

  namespace :matches do
    resources :categories, controller: 'match_categories', only: [:index] do
      collection do
        post :datatables_editor_cud
      end
    end
  end

  resources :matches, only: [:index, :show, :update], controller: 'matches/matches' do
    post :datatables_editor_cud, on: :collection
    get :edit_stats, on: :member
    get :stats, on: :member

    resources :videos, except: [:edit, :update, :show] do
      resources :clips, only: [:index] do
        collection do
          post :datatables_editor_cud
          post :assign_clips_to_players
        end
      end
    end
  end

  resources :clip_categories, only: [:index] do
    post :datatables_editor_cud, on: :collection
  end

  resources :playlists, only: [:index] do
    collection do
      post :datatables_editor_cud
      post :assign_playlists_to_players
    end

    resources :clips, only: [] do
      collection do
        get '/' => :index_on_playlist
        post :datatables_editor_cud_on_playlist
      end
    end
  end

  resources :clips, only: [] do
    collection do
      get :for_me
      get :search
    end

    post :log_player_activity_on, on: :member
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
  end

  resources :users, only: [:show]

  get '/players' => 'users#list_players'
end

app/models/clip.rb
class Clip < ActiveRecord::Base
  belongs_to :video
  belongs_to :category, class_name: 'ClipCategory'

  has_many :clip_players, dependent: :destroy
  has_many :players, through: :clip_players

  has_many :playlist_clips
  has_many :playlists, through: :playlist_clips

  has_many :clip_questions

  include PublicActivity::Common

  # Handles create, update and remove action of DataTables Editor
	# and returns json hash
	# for video
	def self.datatables_editor_cud(dte_action, data, video)
		json_data = {}
		begin
			case dte_action
			when 'create'
				attributes = data[0][1]
				attributes[:start] = Moment.to_seconds(attributes[:start])
				attributes[:end] = Moment.to_seconds(attributes[:end])
				clip = self.new clip_params(attributes)
				clip.video = video
				clip.save!
			when 'edit'
				id = data[0][0]
				attributes = data[0][1]
				attributes[:start] = Moment.to_seconds(attributes[:start])
				attributes[:end] = Moment.to_seconds(attributes[:end])
				clip = self.find(id)
				clip.update clip_params(attributes)
			when 'remove'
				ids = data.collect { |e| e[0] }
				self.where(id: ids).destroy_all
			when 'add_to_playlist'
				data_hash = Hash[data]
				Playlist.find(data_hash['playlist_id']).clips += Clip.find(data_hash['clip_ids'].split(','))
			end
			json_data = { data: [clip.as_json(include: :category)] }
		rescue StandardError => e
			json_data = {
				error: "Ugh!",
				fieldErrors: [{
					name: 'name',
					status: e
				}]
			}
		end
	end

	# Handles create, update and remove action of DataTables Editor
	# and returns json hash
	# for playlist
	def self.datatables_editor_cud_on_playlist(dte_action, data, playlist)
		json_data = {}
		begin
			case dte_action
			when 'remove'
				ids = data.collect { |e| e[0] }
				playlist.clips -= self.where(id: ids)
			end
		rescue StandardError => e
			json_data = { error: e }
		end
		json_data
	end

	# Assign clips to players
	def self.assign_clips_to_players(clip_ids, player_ids)
		players = Player.find(player_ids)
		Clip.find(clip_ids).each { |clip| clip.players += players }
	end

	private

	# Get strong parameters for DataTables Editor CUD
	def self.clip_params(attributes)
		permissibles = [:category_id, :name, :start, :end]
		if attributes.instance_of? ActionController::Parameters
			attributes.permit(permissibles)
		else
			ActionController::Parameters.new(attributes).permit(permissibles)
		end
	end
end

app/models/club.rb
class Club < ActiveRecord::Base
  belongs_to :country
  has_many :matches
  has_many :playlists
  has_many :users
  has_many :players
  has_many :coaches
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :match
  has_many :clips, dependent: :destroy
  has_many :video_questions

  validates :url, uniqueness: true
  validates :ytv_id, uniqueness: true

  before_create :get_video_info

  protected

  def get_video_info
  	ytv = Yt::Video.new url: self.url
  	self.ytv_id = ytv.id
  	[:title, :duration, :thumbnail_url].each do |attr_method|
  		self.send "#{attr_method.to_s}=", ytv.send(attr_method)
  	end
  end
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
	before_action :add_parent_breadcrumb, only: [:index]
	before_action :get_clip_categories, only: [:index]

	# GET
	def index
		current_club = current_user.club
		add_breadcrumb "Clips", match_video_clips_path
		clips = current_video.clips.order(:start)
		@playlists = current_club.playlists.order(:name)
		respond_to do |format|
			format.html
			format.json { render json: { data: clips.as_json(include: :category) } }
		end
	end

	# POST
	# Handles create, update and remove action of DataTables Editor
	# for video
	def datatables_editor_cud
		json_data = Clip.datatables_editor_cud(request.POST[:action], params[:data].to_a, current_video)
		respond_to do |format|
			format.json { render json: json_data }
		end
	end

	# GET
	def index_on_playlist
		add_breadcrumb "Playlists", playlists_path
		add_breadcrumb "Clips", playlist_clips_path
		@clips = current_playlist.clips.order(:id)
		respond_to do |format|
			format.html
			format.json
		end
	end

	# POST
	# Handles create, update and remove action of DataTables Editor
	# for playlist
	def datatables_editor_cud_on_playlist
		json_data = Clip.datatables_editor_cud_on_playlist(request.POST[:action], params[:data].to_a, current_playlist)
		respond_to do |format|
			format.json { render json: json_data }
		end
	end

	# POST
	def assign_clips_to_players
		clip_ids = params[:clip_ids].split(',')
		player_ids = params[:player_ids].split(',')
		Clip.assign_clips_to_players clip_ids, player_ids
		render json: {}
	end

	# GET
	def for_me
		@clips = current_user.becomes(Player).clips.order('clip_players.created_at desc')
	end

	def log_player_activity_on
    Clip.find(params[:id]).create_activity action: :watch, owner: current_user
    render json: {}
	end

	def search
		@matches = current_user.club.matches.order(date: :desc)
		@clip_categories = ClipCategory.all

		clip_category_id = params[:clip_category_id]
		if clip_category_id.present?
			@clips = Clip.where(category_id: clip_category_id)
		end

		if params[:match_id].present?
			video_ids = current_match.videos.pluck(:id)
		else
			video_ids = []
			@matches.each { |match| video_ids += match.videos.pluck(:id) }
		end

		@clips = @clips.where(video_id: video_ids)
	end

	private

	# Add breadcrumbs for parent objects
	def add_parent_breadcrumb
		add_breadcrumb "Matches", current_match
		add_breadcrumb "Videos", match_videos_path
	end

	# Get clip categories
	def get_clip_categories
		@clip_categories = ClipCategory.all.order(:name).collect do |cat|
			{ value: cat.id, label: cat.name }
		end
	end
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/for_me.html.slim
- content_for :page_title, "Clips For Me"

.card-panel.row
	- if @clips.count > 0
		.col.s4: #clips-list-wrapper.nano: .nano-content
			#clips-list.collection.mt-0
				- @clips.each do |clip|
					a.collection-item data-clip-start="#{clip.start}" data-clip-end="#{clip.end}" data-clip-video-url="#{clip.video.url}" data-match-id="#{clip.video.match.id}" href="javascript:void(0)" data-clip-id="#{clip.id}"
						span.title #{clip.name} (#{clip.category.name})
						p
							| Video: #{clip.video.title}
							br
							| Match: #{clip.video.match.name}
		.col.s8#video-clip-wrapper
			video#video-clip.video-js.vjs-default-skin.responsive-embed-16x9.fluid-width(controls preload="auto" data-setup-deferred='{"techOrder": ["youtube"], "sources": [{"type": "video/youtube", "src": "#{@clips[0].video.url}"}] }')
			.row
				.col.s12.center-align
					button#view-stats.btn.waves-effect.waves-light View Match Stats
	- else
		.col.s12
			h3 There are no clips for you to show.

.modal#stats-popup style="overflow: hidden; max-height: 100%;"
	.modal-content
		.p.p-50

app/views/clips/index.html.slim
- content_for :page_title, "Match Video Clips"

.row
	.col.s8
		.card-panel
			table#clips-table.display.table.table-bordered.table-striped.table-hover.fluid-width
				thead: tr
					th
					th Category
					th Name
					th Start
					th End
					th
				tbody
	.col.s4
		.card-panel#clip-preview-panel
			h4.mb-30 Clip Preview
			= react_component 'ClipPreviewWidget', videoUrl: @current_video.url, clipStart: 0, clipEnd: 0, prerender: true

#playlists-popup.modal.mw-500
	= form_tag datatables_editor_cud_match_video_clips_path, remote: true, method: :post do
		= hidden_field_tag :action, 'add_to_playlist'
		= hidden_field_tag "data[clip_ids]", ''
		.modal-content
			= label_tag :playlist_id
			= select_tag "data[playlist_id]", options_from_collection_for_select(@playlists, :id, :name)
		.modal-footer.pr-24.mb-12
			= button_tag 'Add clips to playlist', class: "btn waves-effect waves-light"

#players-popup.modal.bottom-sheet style="display: block;"
	.modal-content
		= form_tag assign_clips_to_players_match_video_clips_path, remote: true do
			= hidden_field_tag :clip_ids, ''
			= hidden_field_tag :player_ids, ''
		table#players-table.display.table.table-bordered.table-striped.table-hover
			thead: tr
				th
				th Name
			tbody

javascript:
	R.clipCategories = #{raw @clip_categories.to_json};
	R.matchId = #{params[:match_id]};
	R.videoId = #{params[:video_id]};

app/views/clips/index_on_playlist.html.slim
- content_for :page_title, "Clips on #{@current_playlist.name}"

card-panel
	table#clips-table.display.table.table-bordered.table-striped.table-hover.fluid-width
		thead: tr
			th
			th Category
			th Name
			th Start
			th End
			th Match
			th Date
		tbody

javascript:
	R.clipCategories = #{raw @clip_categories.to_json};
	R.playlistId = #{params[:playlist_id]};

app/views/clips/search.html.slim
- content_for :page_title, 'Search Clips'

.row: .col.s10.offset-s1: .row
  = form_tag nil, method: :get
    .col.s4
      p Match
      = select_tag :match_id, options_from_collection_for_select(@matches, :id, :name, params[:match_id]), prompt: 'All'
    .col.s4
      p Clip Category
      = select_tag :clip_category_id, options_from_collection_for_select(@clip_categories, :id, :name, params[:clip_category_id]), prompt: 'All'
    .col.s4
      = button_tag 'Search', class: 'btn waves-effect waves-light'

- if params[:match_id]
  .row
    .col.s8
      .card-panel
        table#clips-table.display.table.table-bordered.table-striped.table-hover.fluid-width
          thead: tr
            th Category
            th Name
            th Start
            th End
            th
          tbody
            - @clips.each do |clip|
              tr
                td= clip.category.name
                td= clip.name
                td= Time.at(clip.start).utc.strftime("%H:%M:%S")
                td= Time.at(clip.end).utc.strftime("%H:%M:%S")
                td= link_to 'Preview', 'javascript:;', class: 'preview-clip', data: { clip_start: clip.start, clip_end: clip.end }
    .col.s4
      .card-panel#clip-preview-panel
        h4.mb-30 Clip Preview
        - if @clips.count > 0
          = react_component 'ClipPreviewWidget', videoUrl: @clips[0].video.url, clipStart: 0, clipEnd: 0, prerender: true