config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    unlocks: "users/unlocks"
  }

  devise_scope :user do
    get '/users/add_coach' => 'users/registrations#add_coach'
    post '/users/add_coach' => 'users/registrations#create_coach'
    get '/users/add_player' => 'users/registrations#add_player'
    post '/users/add_player' => 'users/registrations#create_player'
  end

  get '/pages/:id' => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'

  get '/dashboard' => 'dashboard#index_for_coach', constraints: lambda { |request| request.env['warden'].user.is? :coach  }
  get '/dashboard' => 'dashboard#index_for_player', constraints: lambda { |request| request.env['warden'].user.is? :player }
  get '/dashboard' => 'dashboard#index', as: :user_root

  resources :dashboard, only: [:index] do
    put :update_yaybar_hidden_state, on: :collection
  end

  resources :clubs, only: [] do
    collection do
      get :choose_subscription_plan
      post :activate_subscription_plan
      get :players
    end
  end

  namespace :matches do
    resources :categories, controller: 'match_categories', only: [:index] do
      collection do
        post :datatables_editor_cud
      end
    end
  end

  resources :matches, only: [:index, :show, :update], controller: 'matches/matches' do
    post :datatables_editor_cud, on: :collection
    get :edit_stats, on: :member
    get :stats, on: :member

    resources :videos, except: [:edit, :update, :show] do
      resources :clips, only: [:index] do
        collection do
          post :datatables_editor_cud
          post :assign_clips_to_players
        end
      end
    end
  end

  resources :clip_categories, only: [:index] do
    post :datatables_editor_cud, on: :collection
  end

  resources :playlists, only: [:index] do
    collection do
      post :datatables_editor_cud
      post :assign_playlists_to_players
    end

    resources :clips, only: [] do
      collection do
        get '/' => :index_on_playlist
        post :datatables_editor_cud_on_playlist
      end
    end
  end

  resources :clips, only: [] do
    collection do
      get :for_me
      get :search
    end

    post :log_player_activity_on, on: :member
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
  end

  resources :users, only: [:show]

  get '/players' => 'users#list_players'
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :match
  has_many :clips, dependent: :destroy
  has_many :video_questions

  validates :url, uniqueness: true
  validates :ytv_id, uniqueness: true

  before_create :get_video_info

  protected

  def get_video_info
  	ytv = Yt::Video.new url: self.url
  	self.ytv_id = ytv.id
  	[:title, :duration, :thumbnail_url].each do |attr_method|
  		self.send "#{attr_method.to_s}=", ytv.send(attr_method)
  	end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	respond_to :html

	before_action :add_parent_breadcrumb

	include ActionController::Live

	# GET
	def index
		@videos = current_match.videos.order(created_at: :asc)
	end

	# GET
	def new
		add_breadcrumb "Add New", new_match_video_path
	end

	# POST
	def create
		@video = Video.new video_params
		@video.match = current_match

		respond_to do |format|
			begin
				if @video.save
					@uploaded_file = params[:analysis_data]
					unless @uploaded_file.nil?
						filename = Rails.root.join 'tmp', 'upload', 'analysis_data'
						File.open filename, 'wb' do |file|
							file.write @uploaded_file.read
						end
						analyzer = ClipDataAnalysis.new(@video, filename, @uploaded_file.content_type)
						analyzer.analyze
					end
					flash[:notice] = "Video has been successfully added!"
				else
					flash[:alert] = "Could not add video.\\n#{@video.errors.full_messages.join("\\n")}"
				end
			rescue Yt::Errors::RequestError => e
				flash[:alert] = "Youtube video does not seem to be valid."
			end
			respond_with @video, location: match_videos_path
		end
	end

	# DELETE
	def destroy
		@video.destroy
		flash[:notice] = "Video has been deleted."
		redirect_to match_videos_path
	end

	private

	def add_parent_breadcrumb
		add_breadcrumb "Match", self.current_match
		add_breadcrumb "Videos", match_videos_path
	end

	def video_params
		params.require(:video).permit(:url)
	end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_video.html.slim
tr
	td= link_to image_tag(video.thumbnail_url), video.url, target: '_new'
	td.fs-16= video.title
	td= hms video.duration
	td= link_to 'Clips', match_video_clips_path(video.match_id, video.id)
	td= link_to 'Delete', match_video_path(video.match_id, video.id), method: :delete, data: { confirm: "This will delete all associated clip records as well. Are you sure?" }, class: "btn red waves-effect waves-dark"

app/views/videos/index.html.slim
- content_for :page_title, "Match Videos"

.card
	.title
		h4= @current_match.name
		.clear
			| (#{l @current_match.date})
	.card-content
		- unless @videos.empty?
			.table-responsive
				table.table.table-striped
					tbody= render @videos
		- else
			p There are no videos for this match.
	.card-action
		= link_to 'Add New', new_match_video_path, class: "waves-effect waves-light btn z-depth-0 z-depth-1-hover"

app/views/videos/new.html.slim
- content_for :page_title, "Add New Match Video"

= flash_notice
= flash_alert

.row: .col.s8.offset-s2
	.card.small
		= form_for @video, url: match_videos_path(@current_match),
			html: { enctype: 'multipart/form-data' } do |f|
			.card-image
				= image_tag 'match_videos_banner.png'
				.card-title.fluid-width.center-align style="text-shadow: 0 2px 6px #424242, 0 2px 6px #424242;"
					.fs-30.fw-400= @current_match.name
					.fs-16.light= l @current_match.date
			.content
				table.table.table-condensed
					tbody
						tr
							th URL
							td= f.text_field :url
						tr
							th
								| Analysis Data
								.light.fs-12 Supported types: CSV
							td= file_field_tag_v2 'File', :analysis_data
			.card-action
				button.waves-effect.waves-light.btn.z-depth-0.z-depth-1-hover name="commit" type="submit" Add