config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    unlocks: "users/unlocks"
  }

  devise_scope :user do
    get '/users/add_coach' => 'users/registrations#add_coach'
    post '/users/add_coach' => 'users/registrations#create_coach'
    get '/users/add_player' => 'users/registrations#add_player'
    post '/users/add_player' => 'users/registrations#create_player'
  end

  get '/pages/:id' => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'

  get '/dashboard' => 'dashboard#index_for_coach', constraints: lambda { |request| request.env['warden'].user.is? :coach  }
  get '/dashboard' => 'dashboard#index_for_player', constraints: lambda { |request| request.env['warden'].user.is? :player }
  get '/dashboard' => 'dashboard#index', as: :user_root

  resources :dashboard, only: [:index] do
    put :update_yaybar_hidden_state, on: :collection
  end

  resources :clubs, only: [] do
    collection do
      get :choose_subscription_plan
      post :activate_subscription_plan
      get :players
    end
  end

  namespace :matches do
    resources :categories, controller: 'match_categories', only: [:index] do
      collection do
        post :datatables_editor_cud
      end
    end
  end

  resources :matches, only: [:index, :show, :update], controller: 'matches/matches' do
    post :datatables_editor_cud, on: :collection
    get :edit_stats, on: :member
    get :stats, on: :member

    resources :videos, except: [:edit, :update, :show] do
      resources :clips, only: [:index] do
        collection do
          post :datatables_editor_cud
          post :assign_clips_to_players
        end
      end
    end
  end

  resources :clip_categories, only: [:index] do
    post :datatables_editor_cud, on: :collection
  end

  resources :playlists, only: [:index] do
    collection do
      post :datatables_editor_cud
      post :assign_playlists_to_players
    end

    resources :clips, only: [] do
      collection do
        get '/' => :index_on_playlist
        post :datatables_editor_cud_on_playlist
      end
    end
  end

  resources :clips, only: [] do
    collection do
      get :for_me
      get :search
    end

    post :log_player_activity_on, on: :member
  end

  resources :conversations, only: [:create] do
    resources :messages, only: [:create]
  end

  resources :users, only: [:show]

  get '/players' => 'users#list_players'
end

app/views/layouts/side_nav/_club_admin.html.slim
li.label Dashboard

li class="#{cp user_root_path}"
	= link_to user_root_path, class: "waves-effect waves-blue"
		i.fa.fa-dashboard
		| Dashboard

li.label User Management

li class="#{cp edit_user_registration_path}"
	= link_to edit_user_registration_path, class: "waves-effect waves-blue"
		i.fa.fa-cog
		| Edit My Profile

li
	a.yay-sub-toggle.waves-effect.waves-blue
		i.fa.fa-user-plus
		| Add User
		span.yay-collapse-icon.mdi-navigation-expand-more
	ul
		li class="#{cp users_add_coach_path}"
			= link_to 'Coach', users_add_coach_path, class: "waves-effect waves-blue"
		li class="#{cp users_add_player_path}"
			= link_to 'Player', users_add_player_path, class: "waves-effect waves-blue"

li.label Club Management

li class="#{cp choose_subscription_plan_clubs_path}"
	= link_to choose_subscription_plan_clubs_path, class: "waves-effect waves-blue"
		i.fa.fa-cog
		| Manage Subscription Plan

app/views/layouts/side_nav/_coach.html.slim
li.label Dashboard

li class="#{cp user_root_path}"
	= link_to user_root_path, class: "waves-effect waves-blue"
		i.fa.fa-dashboard
		| Dashboard

li.label User

li class="#{cp edit_user_registration_path}"
	= link_to edit_user_registration_path, class: "waves-effect waves-blue"
		i.fa.fa-cog
		| Edit My Profile

li class="#{cp players_path}"
	= link_to players_path, class: "waves-effect waves-blue"
		i.fa.fa-cog
		| Players

li
	a.yay-sub-toggle.waves-effect.waves-blue
		i.fa.fa-user-plus
		| Add User
		span.yay-collapse-icon.mdi-navigation-expand-more
	ul
		li class="#{cp users_add_player_path}"
			= link_to 'Player', users_add_player_path, class: "waves-effect waves-blue"

li.label Matches, Videos, Clips

li class="#{cp matches_categories_path}"
	= link_to matches_categories_path, class: "waves-effect waves-blue"
		i.fa.fa-cog
		| Match Categories

li class="#{cp(matches_path) || cp_against_ca('matches#show', 'matches#stats', 'matches#edit_stats', 'videos#index', 'clips#index')}"
	= link_to matches_path, class: "waves-effect waves-blue"
		i.fa.fa-cog
		| Matches &amp; Videos

li class="#{cp clip_categories_path}"
	= link_to clip_categories_path, class: "waves-effect waves-blue"
		i.fa.fa-cog
		| Clip Categories

li class="#{cp search_clips_path}"
	= link_to search_clips_path, class: "waves-effect waves-blue"
		i.fa.fa-cog
		| Clips

li class="#{cp(playlists_path) || cp_against_ca('clips#index_on_playlist')}"
	= link_to playlists_path, class: "waves-effect waves-blue"
		i.fa.fa-cog
		| Playlists

app/views/layouts/side_nav/_player.html.slim
li.label Dashboard

li class="#{cp user_root_path}"
	= link_to user_root_path, class: "waves-effect waves-blue"
		i.fa.fa-dashboard
		| Dashboard

li.label User

li class="#{cp edit_user_registration_path}"
	= link_to edit_user_registration_path, class: "waves-effect waves-blue"
		i.fa.fa-cog
		| Edit My Profile

li.label Clips

li class="#{cp for_me_clips_path}"
	= link_to for_me_clips_path, class: "waves-effect waves-blue"
		i.fa.fa-cog
		| Match Clips

app/views/layouts/side_nav/_super_admin.html.slim
li.label Menu
li
	a.yay-sub-toggle.waves-effect.waves-blue
		i.fa.fa-dashboard
		| Dashboards
		span.yay-collapse-icon.mdi-navigation-expand-more
	ul
		li: a.waves-effect.waves-blue Dashboard
		li: a.waves-effect.waves-blue Dashboard v1
li: a.waves-effect.waves-blue
	i.fa.fa-magic
	| Widgets
li: a.waves-effect.waves-blue
	i.mdi.mdi-av-web
	| Layouts
	span.badge.new new